spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cccccccoder/demo-app-config-repository.git
          search-paths: /**/**
server:
  port: 8088

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: http://localhost:8089/eureka/